SELECT  distinct  ?keid ?ketitle ?id ?ensembl
WHERE {
    ?ke a aopo:KeyEvent; edam:data_1025 ?object; dc:title ?ketitle; rdfs:label ?keid.
    ?object skos:exactMatch ?id.
    ?id a edam:data_2291; edam:data_2291 ?ensembl.
} 
