SELECT  distinct  ?keid ?ketitle ?id ?ncbi
WHERE {
    ?ke a aopo:KeyEvent; edam:data_1025 ?object; dc:title ?ketitle; rdfs:label ?keid.
    ?object skos:exactMatch ?id.
    ?id a edam:data_1027; edam:data_1027 ?ncbi.
} 
