PREFIX taxon: <http://purl.uniprot.org/taxonomy/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT  distinct ?tax (group_concat(distinct ?name;separator=" | ") as ?names) count(distinct ?keker) as ?n 
WHERE {
    ?keker ncbitaxon:131567 ?taxon2.
?taxon2 a ncbitaxon:131567; dc:title ?name.
BIND (fn:substring(?taxon2,48) as ?tax2)
SERVICE <http://sparql.uniprot.org/sparql/> {
    ?taxon rdfs:subClassOf* taxon:39107 .} #taxon:39107 stands for Murinae. Replace with taxon:9989 for all rodents
BIND (fn:substring(?taxon,34) as ?tax)
FILTER (?tax = ?tax2)
} order by desc (?n)
