PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX prov: <http://www.w3.org/ns/prov#>
SELECT  distinct  ?cas1 ?chemName ?AOPTitle
WHERE {
    ?chem a cheminf:000000 ;
        dc:title ?chemName;
        cheminf:000446 ?cas.
    ?stressor aopo:has_chemical_entity ?chem.
    ?aop a aopo:AdverseOutcomePathway; nci:C54571 ?stressor; dc:title ?AOPTitle.
BIND (fn:substring(?cas,0) as ?cas1)
    SERVICE <https://query.wikidata.org/sparql> {
       ?wdchem wdt:P31 wd:Q407752; wdt:P231 ?cas2.} #Q187661 stands for carcinogen, Q72941151 stands for developmental toxicant, Q35456 stands for essential medicine, Q55427774 for male reproductive toxicant, Q55427776 for female reproductive toxicant, Q407752 for neurotoxin, Q1138899 for endocrine disruptors, 
BIND (fn:substring(?cas2,0) as ?cas3)
FILTER (?cas1 = ?cas3)
} ORDER BY ASC (?chemName)
